spring:
  application:
    name: custom-service

server:
  port: ${PORT}

management:
  server:
    port: ${MANAGE_PORT}
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}
  instance:
    status-page-url-path: /manage/info

custom:
  prop: "development custom prop (changed)"
