spring:
  application:
    name: custom-service

management:
  server:
    port: 7000
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7500/eureka/

custom:
  prop: "development custom prop (changed)"
