spring:
  application:
    name: custom-service

server:
  port: 9000

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"

custom:
  prop: "development custom prop"